/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum Coordinate {
  Absolute = 0,
  Relative = 1
}

export declare function getMousePosition(): MousePosition

export interface MousePosition {
  x: number
  y: number
}

export declare function moveMouseWithPause(x: number, y: number, coordinate: Coordinate): void

export declare function startAutoclicker(intervalMs: number): void

export declare function startAutoclickerWithCoord(intervalMs: number, x: number, y: number): void

export declare function stopAutoclicker(): void
