name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Ex: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd autoclic-app/autoclic && npm ci && npm run build && npm run build:linux:arm && npm run build:win && \
            cd ../ && npm ci && npm run build:linux && npm run build:linux:arm64 && npm run build:win:port

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            autoclic-app/dist/autoclic-app-1.0.0_x86_64.AppImage
            autoclic-app/dist/autoclic-app_1.0.0_amd64.deb
            autoclic-app/dist/autoclic-app-1.0.0.tar.gz
            autoclic-app/dist/autoclic-app-1.0.0_arm64.AppImage
            autoclic-app/dist/autoclic-app_1.0.0_arm64.deb
            autoclic-app/dist/autoclic-app-1.0.0-arm64.tar.gz
            autoclic-app/dist/autoclic-app 1.0.0.exe

  #release:
  #  needs: build
  #  runs-on: ubuntu-latest
#
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
#
  #    - name: Download artifacts
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: binaries
  #        path: ./release-assets
#
  #    - name: Create GitHub Release
  #      uses: softprops/action-gh-release@v1
  #      with:
  #        files: |
  #          release-assets/mon-binaire-rust
  #          release-assets/mon-binaire-zig
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
