name: Build & Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    strategy:
      matrix:
        info:
          - '{ "name": "linux_arm64", "napi_rs_cmd": "build:linux:arm64", "cmd": "build:linux:arm64" }'
          - '{ "name": "linux",       "napi_rs_cmd": "build",             "cmd": "build:linux"       }'
          - '{ "name": "windows",     "napi_rs_cmd": "build:win",         "cmd": "build:win:port"    }'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version autoclic-app/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/gregoire78/autoclic-devcontainer
          cacheFrom: ghcr.io/gregoire78/autoclic-devcontainer
          push: always
          runCmd: |
            cd autoclic-app/autoclic && npm ci && npm run ${{ fromJSON(matrix.info).napi_rs_cmd }} && \
            cd ../ && npm ci && npm run ${{ fromJSON(matrix.info).cmd }}

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ fromJSON(matrix.info).name }}
          path: |
            autoclic-app/dist/*.AppImage
            autoclic-app/dist/*.deb
            autoclic-app/dist/*.tar.gz
            autoclic-app/dist/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
